### ISSUE TITLE
could you explain ?

### ISSUE THREAD

**Issue by jesussuarz** [basharbachir/xenforo-decrypt-users-passwords#1]
Could you explain to me where I'm going to paste this file?

or could you give me access to the video on youtube ..

is private.

**Comment by basharbachir** [comment]
hi Jesus, it's now unlisted so you can now watch it.
https://youtu.be/mkv25mNOP_M

**Comment by jesussuarz** [comment]
i think this doesn't work anymore :(

I did everything like in the video. but the hash still appears to me ...

Any recommendation?

**Comment by basharbachir** [comment]
it's working but you can see the unencrypted passwords just for the new
users or for the users those updated their passwords after you edited the
files.
so that's meaning , that you couldn't know what the passwords for the old
users, unless they changed their password after you edited the files.
or for the new users you must be able to see the passwords without
encryption.
i will take a look to the new version of xenforo later .
may i ask which version you are using?
